
DELETE FROM PUBLIC.cohort WHERE COHORT_DEFINITION_ID = 9201;
INSERT /*+ APPEND */ INTO cohort (
       COHORT_DEFINITION_ID
     , SUBJECT_ID
     , COHORT_START_DATE
     , COHORT_END_DATE
)
SELECT 9201                  AS COHORT_DEFINITION_ID
     , T1.SUBJECT_ID            AS SUBJECT_ID
     , T1.COHORT_START_DATE AS COHORT_START_DATE
     , T1.COHORT_END_DATE   AS COHORT_END_DATE 
  FROM 
      (SELECT 9201 AS COHORT_DEFINITION_ID
              , T1.PERSON_ID AS SUBJECT_ID
              , T1.DEATH_DATE AS COHORT_START_DATE
              , T1.DEATH_DATE + NUMTODSINTERVAL(1, 'day')  AS COHORT_END_DATE 
       FROM cdm.DEATH T1
       UNION ALL
       SELECT 9201 AS COHORT_DEFINITION_ID
           , T1.PERSON_ID AS SUBJECT_ID
           , T2.COHORT_START_DATE+89 AS COHORT_START_DATE
           , T2.COHORT_START_DATE+90 AS COHORT_END_DATE
       FROM cdm.VISIT_OCCURRENCE T1
           JOIN (SELECT * FROM cohort T2 WHERE T2.COHORT_DEFINITION_ID = 4274) T2
               ON T1.PERSON_ID = T2.SUBJECT_ID AND T1.VISIT_START_DATE  BETWEEN T2.COHORT_END_DATE AND T2.COHORT_END_DATE + 90
       WHERE T1.VISIT_CONCEPT_ID = 9203
       GROUP BY T1.PERSON_ID, T2.COHORT_START_DATE
     ) T1
GROUP BY T1.SUBJECT_ID, T1.COHORT_START_DATE, T1.COHORT_END_DATE
; 

COMMIT;