
DELETE FROM PUBLIC.cohort WHERE COHORT_DEFINITION_ID = 9002;
INSERT /*+ APPEND */ INTO cohort (
       COHORT_DEFINITION_ID
     , SUBJECT_ID
     , COHORT_START_DATE
     , COHORT_END_DATE
)
SELECT 9002                  AS COHORT_DEFINITION_ID
     , T1.SUBJECT_ID            AS SUBJECT_ID
     , T1.COHORT_START_DATE+0.001 AS COHORT_START_DATE
     , T1.COHORT_END_DATE   AS COHORT_END_DATE 
  FROM PUBLIC.cohort T1
 WHERE 
     COHORT_DEFINITION_ID = 4274
     AND (COHORT_END_DATE - COHORT_START_DATE) >= 9
; 

COMMIT;