dbms <- "oracle"
user <- "user"
password <- "password"
server <- "127.0.0.1/oracle"

cdmDatabaseSchema <- "cdm"
cdmDatabaseName <- "cdm"
oracleTempSchema <- "user"
cohortDatabaseSchema <- "user"
exposureDatabaseSchema <- "user"
outcomeDatabaseSchema <- "user"
vocaSchema <- "voca"
