r = getOption("repos")
r["CRAN"] = "https://cran.r-project.org"
options(repos = r)
install.packages(c('XML','xml2','usethis', 'covr', 'httr', 'roxygen2', 'rversions'))
install.packages('devtools')
install.packages('ff')
library(devtools)
devtools::install_local('/src/Cyclops-master.zip')
devtools::install_local("/src/FeatureExtraction-master.zip")
devtools::install_local("/src/PatientLevelPrediction-master.zip")
devtools::install_local("/src/BigKnn-master.zip")
#devtools::install_github("OHDSI/FeatureExtraction")
#devtools::install_github("OHDSI/PatientLevelPrediction")
#devtools::install_github("OHDSI/BigKnn")