

CREATE TABLE PUBLIC.DRUG_ERA_PO_DEF AS
WITH TEST_TARGET_COHORT_TABLE AS (
    SELECT T1.*
    FROM PUBLIC.cohort T1
    WHERE T1.COHORT_DEFINITION_ID IN (4274,4284)
) 
SELECT T1.DRUG_CONCEPT_ID AS ATTRIBUTE_DEFINITION_ID
    , 'drug_era only per oral during day -365 through -1 days relative to index: ' || C1.CONCEPT_NAME AS ATTRIBUTE_NAME
FROM cdm.DRUG_ERA_PO T1 
    LEFT JOIN cdm.CONCEPT C1 ON T1.DRUG_CONCEPT_ID = C1.CONCEPT_ID
WHERE EXISTS(SELECT 1 FROM TEST_TARGET_COHORT_TABLE T2 WHERE T1.PERSON_ID = T2.SUBJECT_ID)
    AND T1.DRUG_CONCEPT_ID IS NOT NULL
GROUP BY T1.DRUG_CONCEPT_ID, C1.CONCEPT_NAME;

COMMIT;

CREATE TABLE PUBLIC.DRUG_ERA_PO_ATTR AS
WITH TEST_TARGET_COHORT_TABLE AS (
    SELECT T1.* 
    FROM PUBLIC.cohort T1
    WHERE T1.COHORT_DEFINITION_ID IN (4274,4284)
)
SELECT 
    T2.COHORT_DEFINITION_ID AS COHORT_DEFINITION_ID
    , T2.SUBJECT_ID AS SUBJECT_ID
    , T2.COHORT_START_DATE AS COHORT_START_DATE
    , P1.ATTRIBUTE_DEFINITION_ID AS ATTRIBUTE_DEFINITION_ID
    , 1 AS VALUE_AS_NUMBER
    , MAX(T1.DRUG_ERA_START_DATETIME) AS DRUG_ERA_START_DATETIME
FROM cdm.DRUG_ERA_PO T1
    LEFT JOIN cdm.CONCEPT C1 ON T1.DRUG_CONCEPT_ID = C1.CONCEPT_ID
    LEFT JOIN PUBLIC.DRUG_ERA_PO_DEF P1 ON C1.CONCEPT_ID = P1.ATTRIBUTE_DEFINITION_ID
    JOIN TEST_TARGET_COHORT_TABLE T2 ON T1.PERSON_ID = T2.SUBJECT_ID 
                                        AND T1.DRUG_ERA_START_DATETIME BETWEEN T2.COHORT_START_DATE - 365 AND T2.COHORT_START_DATE - 1 
WHERE P1.ATTRIBUTE_DEFINITION_ID IS NOT NULL
GROUP BY T2.COHORT_DEFINITION_ID, T2.SUBJECT_ID, T2.COHORT_START_DATE, P1.ATTRIBUTE_DEFINITION_ID ORDER BY ATTRIBUTE_DEFINITION_ID;

COMMIT;